[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Netlify Functions Plugin to handle function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# PayFast redirect pages (must be before catch-all)
[[redirects]]
  from = "/payfast-redirect-success.html"
  to = "/payfast-redirect-success.html"
  status = 200
  force = true

[[redirects]]
  from = "/payfast-redirect-cancel.html"
  to = "/payfast-redirect-cancel.html"
  status = 200
  force = true

# SPA redirects for React Router (catch-all, must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for CORS and security
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"