# Trigger workflow run at 2025-08-13 
name: Build and Deploy iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Install dependencies
        run: npm install

      - name: Clean and install pods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build and archive
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          cd ios
          fastlane build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ./build.ipa
